### ISSUE TITLE
Such package already exists?

### ISSUE THREAD

**Issue by RomanSek** [ClearcodeHQ/pytest-repeater#72]
I'm not sure that it's functionally the same, but are you aware there's a https://github.com/pytest-dev/pytest-repeat/ plugin? Description looks similar. If your pluin does something differently you may want to mention that plugin and point out differences in `README.rst`.

**Comment by fizyk** [comment]
Hmmm, after creating the pytest-repeater we weren't observing for any new packages providing this feature. pytest-repeat seems to be newer and on pytest-dev. We might actually want to deprecate pytest-repeater in favour of pytest-repeat, since the api seems to be the same.

**Comment by fizyk** [comment]
Judging by the source code, pytest-repeat was created later than repeater.

**Comment by fizyk** [comment]
pytest-repeater has been deprecated
